name: React app deployement

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy react app to github pages
      uses: ehsandeep/deploy-react-to-ghpages@master